In [ ]:
import pandas as pd
import numpy as np 
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

The following settings will improve the default style and font sizes for our charts.

In [ ]:
# sns.set_style('darkgrid')
# matplotlib.rcParams['font.size'] = 14
# matplotlib.rcParams['figure.figsize'] = (10, 6)
# matplotlib.rcParams['figure.facecolor'] = '#00000000'

In [ ]:
df = pd.read_csv('WineQT.csv')

In [ ]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  Id  
0      9.4        5   0  
1      9.8        5   1  
2      9.8        5   2  
3      9.8        6   3  
4      9.4        5   4

In [ ]:
df.drop('Id', axis= 1, inplace= True)

**Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop('quality', axis= 1)
y = df['quality']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.2, random_state= 0)

In [ ]:
(y_test == 3).sum()

1

**Oversampling by SMOTE**

In [ ]:
from imblearn.over_sampling import SMOTE 

In [ ]:
unique, count = np.unique(y_train, return_counts= True)
y_train_dict_value_count = {k:v for (k,v) in zip(unique, count)}
y_train_dict_value_count

{3: 5, 4: 26, 5: 383, 6: 370, 7: 116, 8: 14}

In [ ]:
sm = SMOTE("minority", k_neighbors = 4)

/usr/local/lib/python3.7/dist-packages/imblearn/utils/_validation.py:591: FutureWarning: Pass sampling_strategy=minority as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning,


In [ ]:
X_train_res1, y_train_res1 = sm.fit_resample(X_train, y_train)
X_train_res2, y_train_res2 = sm.fit_resample(X_train_res1,y_train_res1)
X_train_res3, y_train_res3 = sm.fit_resample(X_train_res2,y_train_res2)
X_train_res4, y_train_res4 = sm.fit_resample(X_train_res3,y_train_res3)

In [ ]:
unique, count = np.unique(y_train_res4, return_counts= True)
y_train_smote_value_count = {k:v for (k,v) in zip(unique, count)}
y_train_smote_value_count

{3: 383, 4: 383, 5: 383, 6: 370, 7: 383, 8: 383}

**Decision Tree**

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train_res4, y_train_res4)

DecisionTreeClassifier()

In [ ]:
y_train_pred = dt.predict(X_train_res4)
print('Confusion Matrix: \n',confusion_matrix(y_train_res4, y_train_pred))
print('Accuracy Score: ', dt.score(X_train_res4, y_train_res4))

Confusion Matrix: 
 [[383   0   0   0   0   0]
 [  0 383   0   0   0   0]
 [  0   0 383   0   0   0]
 [  0   0   0 370   0   0]
 [  0   0   0   0 383   0]
 [  0   0   0   0   0 383]]
Accuracy Score:  1.0


In [ ]:
y_test_pred = dt.predict(X_test)
print('Confusion Matrix: \n',confusion_matrix(y_test, y_test_pred))
print('Accuracy Score: ', dt.score(X_test, y_test))

Confusion Matrix: 
 [[ 0  0  1  0  0  0]
 [ 1  0  3  3  0  0]
 [ 1 10 59 30  0  0]
 [ 2  6 17 48 18  1]
 [ 0  1  2  7 16  1]
 [ 0  0  1  0  0  1]]
Accuracy Score:  0.5414847161572053


In [ ]:
max_depth_range = np.arange(1,20,1)
for x in max_depth_range:
  dt = DecisionTreeClassifier(max_depth= x)
  dt.fit(X_train_res4, y_train_res4)
  print('for max_depth: ', x)
  print('Accuracy Score train: ', dt.score(X_train_res4, y_train_res4))
  print('Accuracy Score test: ', dt.score(X_test, y_test))
  print()

for max_depth:  1
Accuracy Score train:  0.33522975929978116
Accuracy Score test:  0.008733624454148471

for max_depth:  2
Accuracy Score train:  0.4188183807439825
Accuracy Score test:  0.15283842794759825

for max_depth:  3
Accuracy Score train:  0.5483588621444201
Accuracy Score test:  0.2663755458515284

for max_depth:  4
Accuracy Score train:  0.612691466083151
Accuracy Score test:  0.36681222707423583

for max_depth:  5
Accuracy Score train:  0.6822757111597374
Accuracy Score test:  0.3930131004366812

for max_depth:  6
Accuracy Score train:  0.7553610503282275
Accuracy Score test:  0.4017467248908297

for max_depth:  7
Accuracy Score train:  0.8135667396061269
Accuracy Score test:  0.4366812227074236

for max_depth:  8
Accuracy Score train:  0.8722100656455142
Accuracy Score test:  0.5021834061135371

for max_depth:  9
Accuracy Score train:  0.912035010940919
Accuracy Score test:  0.5152838427947598

for max_depth:  10
Accuracy Score train:  0.9466083150984683
Accuracy Score tes

Again the decision Tree model is not good

In [ ]:
(y_test == 4).sum()

7

In [ ]:
y_test_pred = dt.predict(X_test)
print(classification_report(y_test, y_test_pred))
print('Confusion Matrix: \n',confusion_matrix(y_test, y_test_pred))
print('Accuracy Score: ', dt.score(X_test, y_test))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         7
           5       0.68      0.60      0.64       100
           6       0.56      0.53      0.55        92
           7       0.55      0.63      0.59        27
           8       0.25      0.50      0.33         2

    accuracy                           0.55       229
   macro avg       0.34      0.38      0.35       229
weighted avg       0.59      0.55      0.57       229

Confusion Matrix: 
 [[ 0  0  1  0  0  0]
 [ 1  0  3  3  0  0]
 [ 0  9 60 31  0  0]
 [ 2  5 20 49 14  2]
 [ 0  2  3  4 17  1]
 [ 0  0  1  0  0  1]]
Accuracy Score:  0.5545851528384279


**Random Forest Classifier**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_res4, y_train_res4)

RandomForestClassifier()

In [ ]:
y_train_pred = rf.predict(X_train_res4)
print('Confusion Matrix: \n',confusion_matrix(y_train_res4, y_train_pred))
print('Accuracy Score: ', rf.score(X_train_res4, y_train_res4))

Confusion Matrix: 
 [[383   0   0   0   0   0]
 [  0 383   0   0   0   0]
 [  0   0 383   0   0   0]
 [  0   0   0 370   0   0]
 [  0   0   0   0 383   0]
 [  0   0   0   0   0 383]]
Accuracy Score:  1.0


In [ ]:
y_test_pred = rf.predict(X_test)
print('Confusion Matrix: \n',confusion_matrix(y_test, y_test_pred))
print('Accuracy Score: ', rf.score(X_test, y_test))

Confusion Matrix: 
 [[ 0  0  1  0  0  0]
 [ 1  0  3  3  0  0]
 [ 1  8 70 21  0  0]
 [ 2  5 16 49 19  1]
 [ 0  0  2  6 19  0]
 [ 0  0  0  1  0  1]]
Accuracy Score:  0.6069868995633187


In [ ]:
max_depth_range = np.arange(1,15,1)
for x in max_depth_range:
  dt = RandomForestClassifier(max_depth= x)
  dt.fit(X_train_res4, y_train_res4)
  print('for max_depth: ', x)
  print('Accuracy Score train: ', dt.score(X_train_res4, y_train_res4))
  print('Accuracy Score test: ', dt.score(X_test, y_test))
  print()

for max_depth:  1
Accuracy Score train:  0.4350109409190372
Accuracy Score test:  0.14410480349344978

for max_depth:  2
Accuracy Score train:  0.5610503282275712
Accuracy Score test:  0.2314410480349345

for max_depth:  3
Accuracy Score train:  0.6437636761487965
Accuracy Score test:  0.37554585152838427

for max_depth:  4
Accuracy Score train:  0.7168490153172866
Accuracy Score test:  0.4192139737991266

for max_depth:  5
Accuracy Score train:  0.7929978118161926
Accuracy Score test:  0.44541484716157204

for max_depth:  6
Accuracy Score train:  0.8516411378555798
Accuracy Score test:  0.48034934497816595

for max_depth:  7
Accuracy Score train:  0.9072210065645514
Accuracy Score test:  0.5283842794759825

for max_depth:  8
Accuracy Score train:  0.9409190371991247
Accuracy Score test:  0.5545851528384279

for max_depth:  9
Accuracy Score train:  0.973741794310722
Accuracy Score test:  0.5676855895196506

for max_depth:  10
Accuracy Score train:  0.9864332603938731
Accuracy Score tes

In this case max_depth = 9 is best.

In [ ]:
rf = RandomForestClassifier(max_depth= 9)
rf.fit(X_train_res4, y_train_res4)
y_train_pred = rf.predict(X_train_res4)
print('Confusion Matrix: \n',confusion_matrix(y_train_res4, y_train_pred))
print('Accuracy Score train: ', rf.score(X_train_res4, y_train_res4))


Confusion Matrix: 
 [[383   0   0   0   0   0]
 [  2 380   1   0   0   0]
 [  8   3 359   9   4   0]
 [  3   0   4 351   7   5]
 [  0   0   0   2 370  11]
 [  0   0   0   0   1 382]]
Accuracy Score train:  0.973741794310722


In [ ]:
y_test_pred = rf.predict(X_test)
print(classification_report(y_test, y_test_pred))
print('Confusion Matrix: \n',confusion_matrix(y_test, y_test_pred))
print('Accuracy Score test: ', rf.score(X_test, y_test))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.06      0.14      0.09         7
           5       0.76      0.66      0.71       100
           6       0.61      0.55      0.58        92
           7       0.50      0.63      0.56        27
           8       0.33      0.50      0.40         2

    accuracy                           0.59       229
   macro avg       0.38      0.41      0.39       229
weighted avg       0.64      0.59      0.61       229

Confusion Matrix: 
 [[ 0  0  1  0  0  0]
 [ 1  1  3  2  0  0]
 [ 1  9 66 23  1  0]
 [ 3  6 14 51 16  2]
 [ 0  0  3  7 17  0]
 [ 0  0  0  1  0  1]]
Accuracy Score test:  0.5938864628820961


**Gradient Boosting**

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier()
gb.fit(X_train_res4, y_train_res4)

GradientBoostingClassifier()

In [ ]:
y_train_pred = gb.predict(X_train_res4)
print('Confusion Matrix: \n',confusion_matrix(y_train_res4, y_train_pred))
print('Accuracy Score: ', gb.score(X_train_res4, y_train_res4))

Confusion Matrix: 
 [[383   0   0   0   0   0]
 [  0 382   0   1   0   0]
 [  0   8 334  35   6   0]
 [  0   2  37 308  21   2]
 [  0   0   1   7 372   3]
 [  0   0   0   0   0 383]]
Accuracy Score:  0.9461706783369803


In [ ]:
y_test_pred = gb.predict(X_test)
print('Confusion Matrix: \n',confusion_matrix(y_test, y_test_pred))
print('Accuracy Score: ', gb.score(X_test, y_test))

Confusion Matrix: 
 [[ 0  0  1  0  0  0]
 [ 1  0  3  3  0  0]
 [ 1  8 67 22  0  2]
 [ 1  5 15 48 21  2]
 [ 0  0  1  9 16  1]
 [ 0  0  0  1  0  1]]
Accuracy Score:  0.5764192139737991


In [ ]:
%%time
max_depth_range = np.arange(1,15,1)
for x in max_depth_range:
  dt = GradientBoostingClassifier(max_depth= x)
  dt.fit(X_train_res4, y_train_res4)
  print('for max_depth: ', x)
  print('Accuracy Score train: ', dt.score(X_train_res4, y_train_res4))
  print('Accuracy Score test: ', dt.score(X_test, y_test))
  print()

for max_depth:  1
Accuracy Score train:  0.7422319474835887
Accuracy Score test:  0.4847161572052402

for max_depth:  2
Accuracy Score train:  0.8669584245076587
Accuracy Score test:  0.5283842794759825

for max_depth:  3
Accuracy Score train:  0.9461706783369803
Accuracy Score test:  0.5764192139737991

for max_depth:  4
Accuracy Score train:  0.9859956236323851
Accuracy Score test:  0.6069868995633187

for max_depth:  5
Accuracy Score train:  1.0
Accuracy Score test:  0.6375545851528385

for max_depth:  6
Accuracy Score train:  1.0
Accuracy Score test:  0.6244541484716157

for max_depth:  7
Accuracy Score train:  1.0
Accuracy Score test:  0.6069868995633187

for max_depth:  8
Accuracy Score train:  1.0
Accuracy Score test:  0.6200873362445415

for max_depth:  9
Accuracy Score train:  1.0
Accuracy Score test:  0.5851528384279476

for max_depth:  10
Accuracy Score train:  1.0
Accuracy Score test:  0.5851528384279476

for max_depth:  11
Accuracy Score train:  1.0
Accuracy Score test:  0

Max Depth 3 is best according to the accuracy


In [ ]:
gb = GradientBoostingClassifier(max_depth= 3)
gb.fit(X_train_res4, y_train_res4)

GradientBoostingClassifier()

In [ ]:
y_train_pred = gb.predict(X_train_res4)
print('Confusion Matrix: \n',confusion_matrix(y_train_res4, y_train_pred))
print('Accuracy Score: ', gb.score(X_train_res4, y_train_res4))

Confusion Matrix: 
 [[383   0   0   0   0   0]
 [  0 382   0   1   0   0]
 [  0   8 334  35   6   0]
 [  0   2  37 308  21   2]
 [  0   0   1   7 372   3]
 [  0   0   0   0   0 383]]
Accuracy Score:  0.9461706783369803


In [ ]:
y_test_pred = gb.predict(X_test)
print(classification_report(y_test, y_test_pred))
print('Confusion Matrix: \n',confusion_matrix(y_test, y_test_pred))
print('Accuracy Score: ', gb.score(X_test, y_test))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         7
           5       0.77      0.67      0.72       100
           6       0.58      0.52      0.55        92
           7       0.43      0.59      0.50        27
           8       0.17      0.50      0.25         2

    accuracy                           0.58       229
   macro avg       0.32      0.38      0.34       229
weighted avg       0.62      0.58      0.59       229

Confusion Matrix: 
 [[ 0  0  1  0  0  0]
 [ 1  0  3  3  0  0]
 [ 1  8 67 22  0  2]
 [ 1  5 15 48 21  2]
 [ 0  0  1  9 16  1]
 [ 0  0  0  1  0  1]]
Accuracy Score:  0.5764192139737991


**XG Boost**

In [ ]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train_res4, y_train_res4)

XGBClassifier(objective='multi:softprob')

In [ ]:
y_train_pred = xgb.predict(X_train_res4)
print('Confusion Matrix: \n',confusion_matrix(y_train_res4, y_train_pred))
print('Accuracy Score: ', xgb.score(X_train_res4, y_train_res4))

Confusion Matrix: 
 [[383   0   0   0   0   0]
 [  2 381   0   0   0   0]
 [  9  18 294  49  13   0]
 [  2   6  58 245  50   9]
 [  0   4   1   7 357  14]
 [  0   0   0   0   2 381]]
Accuracy Score:  0.8932166301969365


In [ ]:
y_test_pred = xgb.predict(X_test)
print(classification_report(y_test, y_test_pred))
print('Confusion Matrix: \n',confusion_matrix(y_test, y_test_pred))
print('Accuracy Score: ', xgb.score(X_test, y_test))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.06      0.14      0.08         7
           5       0.77      0.61      0.68       100
           6       0.55      0.42      0.48        92
           7       0.39      0.67      0.49        27
           8       0.12      0.50      0.20         2

    accuracy                           0.52       229
   macro avg       0.32      0.39      0.32       229
weighted avg       0.61      0.52      0.55       229

Confusion Matrix: 
 [[ 0  1  0  0  0  0]
 [ 1  1  2  3  0  0]
 [ 4  8 61 22  3  2]
 [ 3  7 15 39 25  3]
 [ 0  0  1  6 18  2]
 [ 0  0  0  1  0  1]]
Accuracy Score:  0.5240174672489083


In [ ]:
max_depth_range = np.arange(1,15,1)
for x in max_depth_range:
  dt = XGBClassifier(max_depth= x)
  dt.fit(X_train_res4, y_train_res4)
  print('for max_deoth: ', x)
  print('Accuracy Score train: ', dt.score(X_train_res4, y_train_res4))
  print('Accuracy Score test: ', dt.score(X_test, y_test))
  print()

for max_deoth:  1
Accuracy Score train:  0.7032822757111598
Accuracy Score test:  0.43231441048034935

for max_deoth:  2
Accuracy Score train:  0.8148796498905908
Accuracy Score test:  0.5065502183406113

for max_deoth:  3
Accuracy Score train:  0.8932166301969365
Accuracy Score test:  0.5240174672489083

for max_deoth:  4
Accuracy Score train:  0.9518599562363238
Accuracy Score test:  0.5545851528384279

for max_deoth:  5
Accuracy Score train:  0.9816192560175054
Accuracy Score test:  0.5938864628820961

for max_deoth:  6
Accuracy Score train:  0.9991247264770241
Accuracy Score test:  0.5720524017467249

for max_deoth:  7
Accuracy Score train:  1.0
Accuracy Score test:  0.5633187772925764

for max_deoth:  8
Accuracy Score train:  1.0
Accuracy Score test:  0.5807860262008734

for max_deoth:  9
Accuracy Score train:  1.0
Accuracy Score test:  0.5807860262008734

for max_deoth:  10
Accuracy Score train:  1.0
Accuracy Score test:  0.6069868995633187

for max_deoth:  11
Accuracy Score trai

In [ ]:
xgb = XGBClassifier(max_depth= 5)
xgb.fit(X_train_res4, y_train_res4)

XGBClassifier(max_depth=5, objective='multi:softprob')

In [ ]:
y_train_pred = xgb.predict(X_train_res4)
print('Confusion Matrix: \n',confusion_matrix(y_train_res4, y_train_pred))
print('Accuracy Score: ', xgb.score(X_train_res4, y_train_res4))

Confusion Matrix: 
 [[383   0   0   0   0   0]
 [  0 383   0   0   0   0]
 [  0   1 364  17   1   0]
 [  0   0  12 350   8   0]
 [  0   0   0   1 380   2]
 [  0   0   0   0   0 383]]
Accuracy Score:  0.9816192560175054


In [ ]:
y_test_pred = xgb.predict(X_test)
print(classification_report(y_test, y_test_pred))
print('Confusion Matrix: \n',confusion_matrix(y_test, y_test_pred))
print('Accuracy Score: ', xgb.score(X_test, y_test))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         7
           5       0.75      0.69      0.72       100
           6       0.57      0.54      0.56        92
           7       0.46      0.59      0.52        27
           8       0.33      0.50      0.40         2

    accuracy                           0.59       229
   macro avg       0.35      0.39      0.37       229
weighted avg       0.62      0.59      0.60       229

Confusion Matrix: 
 [[ 0  0  0  1  0  0]
 [ 1  0  3  3  0  0]
 [ 1  6 69 23  1  0]
 [ 1  3 18 50 18  2]
 [ 0  0  2  9 16  0]
 [ 0  0  0  1  0  1]]
Accuracy Score:  0.5938864628820961


From the above analysis, it is clear that XG perform best on the dataset

**SVM**

In [ ]:

from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train_res4, y_train_res4)

SVC()

In [ ]:
y_train_pred = svc.predict(X_train_res4)
print('Confusion Matrix: \n',confusion_matrix(y_train_res4, y_train_pred))
print('Accuracy Score: ', svc.score(X_train_res4, y_train_res4))

Confusion Matrix: 
 [[322  30   0  31   0   0]
 [ 86 158  22  33  62  22]
 [117  85  83  35  33  30]
 [ 88  57  17  68  75  65]
 [ 27  36  17  34 121 148]
 [ 20  19   1   3  85 255]]
Accuracy Score:  0.44070021881838073


In [ ]:
y_test_pred = svc.predict(X_test)
print('Confusion Matrix: \n',confusion_matrix(y_test, y_test_pred))
print('Accuracy Score: ', svc.score(X_test, y_test))

Confusion Matrix: 
 [[ 0  1  0  0  0  0]
 [ 1  1  0  3  1  1]
 [34 22 18 17  3  6]
 [22 12  2 18 25 13]
 [ 1  3  2  1 11  9]
 [ 0  0  0  1  0  1]]
Accuracy Score:  0.21397379912663755


In [ ]:
def with_kernel(kernel):
  for x in ['rbf', 'linear', 'poly']:
    svc = SVC(kernel = x)
    svc.fit(X_train_res4, y_train_res4)
    print('for kernel', x)
    print('Accuracy Score: ', svc.score(X_train_res4, y_train_res4))
    print('Accuracy Score: ', svc.score(X_test, y_test))
    print()

In [ ]:
Kernel_list = ['rbf', 'linear', 'poly']

In [ ]:
with_kernel(Kernel_list)

for kernel rbf
Accuracy Score:  0.44070021881838073
Accuracy Score:  0.21397379912663755

for kernel linear
Accuracy Score:  0.6070021881838075
Accuracy Score:  0.4585152838427948

for kernel poly
Accuracy Score:  0.3400437636761488
Accuracy Score:  0.1615720524017467



It means SVM is the Poorest Model for this dataset

In [ ]:
X_test.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
946            9.1             0.775         0.22             2.2      0.079   
142            6.9             1.090         0.06             2.1      0.061   
934            9.1             0.760         0.68             1.7      0.414   
625            9.0             0.800         0.12             2.4      0.083   
124            7.3             0.380         0.21             2.0      0.080   

     free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
946                 12.0                  48.0  0.99760  3.18       0.51   
142                 12.0                  31.0  0.99480  3.51       0.43   
934                 18.0                  64.0  0.99652  2.90       1.33   
625                  8.0                  28.0  0.99836  3.33       0.65   
124                  7.0                  35.0  0.99610  3.33       0.47   

     alcohol  
946      9.6  
142     11.4  
934      9.1  
625     10.4  
124      9.5

In [ ]:
y_test.head()

946    5
142    4
934    6
625    6
124    5
Name: quality, dtype: int64

In [ ]:
X_test.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

**Prediction on Single Data-Set**

Lets take data from test set and modified it little bit and then predict this on this single input

In [ ]:
new_input = {'fixed acidity': 9,
            'volatile acidity': 0.801,
            'citric acid': 0.11,
            'residual sugar': 2.2,
            'chlorides': 0.08,
            'free sulfur dioxide': 8.1,
            'total sulfur dioxide': 27,
            'density': 0.99,
            'pH': 3.3,
            'sulphates': 0.6,
            'alcohol': 10}

In [ ]:
new_input_df = pd.DataFrame([new_input])
new_input_df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0              9             0.801         0.11             2.2       0.08   

   free sulfur dioxide  total sulfur dioxide  density   pH  sulphates  alcohol  
0                  8.1                    27     0.99  3.3        0.6       10

In [ ]:
prediction = xgb.predict(new_input_df)[0]
prediction

3